# Generated by Django 4.1.5 on 2023-01-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family_members',
            name='age',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='family_members',
            name='alive',
            field=models.IntegerField(null=True),
        ),
    ]
